# Edit this file directly from GitHub as editing in windows seems to corrupt it (probably a BOM)

[[redirects]]
  from = "/rss"
  to = "/rss.xml"
  status = 200

[[redirects]]
  from = "/building-a-blog-on-github-discussions"
  to = "/building-a-github-discussions-powered-blog"
